# Exercise 2.B Cleaning up data

In [34]:
#importing libraries
import numpy as np
import pandas as pd

In [36]:
#creating a new df
df = pd.read_csv("test_data.csv") #using test_data for df
df #displaying output

   ID     Name   Age       City  Store
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [38]:
#showing column statistics
df.describe() #using describe to show column statistics

            ID       Age      Store
count  8.00000   6.00000   7.000000
mean   4.50000  25.00000  66.285714
std    2.44949   6.78233  32.576650
min    1.00000  18.00000  -1.000000
25%    2.75000  19.75000  60.000000
50%    4.50000  23.50000  78.000000
75%    6.25000  29.50000  87.500000
max    8.00000  35.00000  92.000000

## Filtering a DataFrame

In [41]:
#filtering df to show age GREATER THAN 18
df[df['Age']>18] #age greater than 18

   ID     Name   Age     City  Store
0   1   Alicia  25.0       NY   85.0
2   3  Charlie  22.0  Chicago   -1.0
3   4  Dominic  19.0  Houston   65.0
4   5      Eve  31.0  Phoenix   78.0
5   6    Frank  35.0   Boston    NaN

In [43]:
#filtering df show only Stores GREATER THAN 50 & LESS THAN 100
df[(df['Store']>50) & (df['Store']<100)] #greater than 50, less than 100

   ID     Name   Age       City  Store
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

## Modifying a DataFrame

In [46]:
#creating new variable to clean
df_cleaned = df.drop(df[df['Store']<0].index) #dropping Stores below 0
df_cleaned #displaying output

   ID     Name   Age       City  Store
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [48]:
#cleaning more of the data
df_cleaned = df_cleaned.drop(columns=['City']) #dropping City column
df_cleaned #displaying output

   ID     Name   Age  Store
0   1   Alicia  25.0   85.0
1   2      Bob   NaN   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace   NaN   55.0
7   8    Heidi  18.0   90.0

In [50]:
#replacing missing values
df_cleaned['Age'] = df_cleaned['Age'].fillna(df_cleaned['Age'].mean()) #replacing missing age values
df_cleaned #displaying results

   ID     Name   Age  Store
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [52]:
#replacing 0 values
df_cleaned['Store'] = df_cleaned['Store'].replace(0,df_cleaned['Store'].mean()) #replacing 0 values in Store
df_cleaned #displaying output

   ID     Name   Age  Store
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [54]:
#dropping NaN values
df_cleaned = df_cleaned.dropna() #using dropna to drop NaN
df_cleaned #displaying output

   ID     Name   Age  Store
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [56]:
#taking ID values as index labels
df_cleaned = df_cleaned.set_index('ID')
df_cleaned = df_cleaned.drop(columns=['ID'],errors='ignore') #ignoring errors and dropping column
df_cleaned

       Name   Age  Store
ID
1    Alicia  25.0   85.0
2       Bob  25.6   92.0
4   Dominic  19.0   65.0
5       Eve  31.0   78.0
7     Grace  25.6   55.0
8     Heidi  18.0   90.0